// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnolrtsgqvwcbqdtdudu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRub2xydHNncXZ3Y2JxZHRkdWR1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2NjM0OTksImV4cCI6MjA1NjIzOTQ5OX0.6FE-Olxh-OGyoudF-lzVKe61x2vvpeKcdQ0xut8e3Zw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);